praise = ['You\'ve got it made', 'Super', 'That\'s good', 'You\'re really working hard today',
          'Good work', 'I\'m happy to see you working like that', 'I\'m proud of the way you are working today',
          'You\'re doing a good job', 'That\'s it', 'That\'s quite an improvement', 'Great',
          'I knew you could do it', 'Congratulations', 'Now you have it', 'You are learning fast',
          'Couldn\'t have done it better myself', 'You should be proud of yourself',
          'That\'s the right way to do it', 'You\'re getting better every day', 'Nice going', 'Wow',
          'That\'s the way', 'Keep up the good work', 'Terrific', 'Nothing can stop you now', 'Sensational',
          'That was first class work', 'Excellent', 'Perfect', 'Wonderful', 'You did that very well', 'Fine',
          'Outstanding', 'Fantastic', 'Tremendous', 'That\'s how to handle that', 'Right on',
          'You\'re doing beautifully', 'Superb', 'You certainly did well today', 'Keep it up',
          'You got it right', 'Well, look at you go', 'That\'s it', 'I\'m very proud of you', 'Marvelous',
          'I like that', 'You\'re doing fine', 'Good job', 'That\'s really nice',
          'That kind of work makes me happy', 'You\’re good', 'Now that’s what I call a fine job',
          'I\’m impressed with your progress', 'Incredible job', 'Awesome job', 'How extraordinary',
          'Amazing', 'Unbelievable work', 'Phenomenal', 'You\'re special', 'Cool', 'You\'ve outdone yourself',
          'Thumbs up', 'What a great learner', 'Fabulous', 'You made it happen', 'Bravo', 'You\'re unique',
          'Exceptional', 'Breathtaking', 'You\'re a great example for others', 'Keep up the good work',
          'I knew you had it in you', 'You\'ve made progress', 'Very good', 'What a genius', 'Super job',
          'Well done', 'You\'re inspiring', 'Hooray for you', 'You\'re a joy', 'You\'re a shining star',
          'You\'re amazing', 'You\'ve got what it takes', 'Spectacular work', 'Remarkable', 'Clever',
          'Smart', 'Magnificent', 'Brilliant', 'You\'re a pleasure to know', 'You\'re very talented',
          'You\'re a champ', 'You\'re the greatest']